import { GoogleGenAI, Type } from "@google/genai";
import { AnalysisResult, PropertyData, LeaseData } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export async function generateLeaseAgreement(data: LeaseData): Promise<string> {
  const prompt = `
    Generate a professional residential lease agreement based on the following details:
    Landlord: ${data.landlordName}
    Tenant: ${data.tenantName}
    Property Address: ${data.propertyAddress}
    Monthly Rent: $${data.rentAmount}
    Lease Duration: ${data.leaseDuration}
    Security Deposit: $${data.securityDeposit}
    Start Date: ${data.startDate}
    Specific Clauses/Notes: ${data.specificClauses}

    The agreement should be formal, comprehensive, and include standard sections like:
    - Parties and Property
    - Term of Lease
    - Rent and Security Deposit
    - Maintenance and Repairs
    - Rules and Regulations
    - Termination
    - Signatures

    IMPORTANT: Include a prominent disclaimer at the beginning stating: "DISCLAIMER: This document is a template generated by AI for informational purposes only. It does not constitute legal advice. Laws regarding lease agreements vary by jurisdiction. You MUST consult with a qualified legal professional in your area before using or signing this document."
    
    Format the output in clean Markdown.
  `;

  const response = await ai.models.generateContent({
    model: "gemini-2.0-flash-exp",
    contents: prompt,
  });

  return response.text;
}

export async function analyzeProperty(data: PropertyData): Promise<AnalysisResult> {
  const prompt = `
    Analyze this real estate investment property:
    Address: ${data.address}
    Purchase Price: $${data.purchasePrice}
    Down Payment: ${data.downPaymentPercent}%
    Interest Rate: ${data.interestRate}%
    Loan Term: ${data.loanTermYears} years
    HOA: $${data.hoaMonthly}/mo

    Use Google Search to find:
    1. Property specs (sqft, beds, baths, year built, lot size).
    2. AT LEAST THREE comparable rental properties within a 2-mile radius. List their advertised rents, property types, and key features.
    3. Use these comparables to provide a more accurate market rent estimate for the subject property.
    4. Tax and insurance estimates for this location.
    5. Market trends (appreciation, vacancy, and specific growth drivers like new infrastructure, job growth, or demographic shifts).
    6. Provide a list of specific growth trends for this area.
    7. Provide AI-driven forecasting for the next 1-5 years:
       - Predicted annual appreciation rates.
       - Predicted rental demand scores (1-100) and market sentiment.
       - A detailed 5-year outlook summary.

    Calculate:
    - Cap Rate: NOI / Purchase Price
    - Cash-on-Cash Return: Annual Pre-tax Cash Flow / Total Cash Invested
    - Gross Rent Multiplier: Price / (Market Rent * 12)
    - Debt Service Coverage Ratio: NOI / Annual Debt Service
    - Operating Expense Ratio: (Total Expenses - Debt Service) / Gross Income

    Assumptions:
    - Maintenance: ${data.maintenancePercent}% of gross rent
    - Vacancy: ${data.vacancyPercent}%
    - CapEx: ${data.capExPercent}%
    - Property Management: ${data.managementPercent}%

    Provide a "BUY" or "PASS" recommendation based on a target 8% Cap Rate or 10% CoC.
  `;

  const response = await ai.models.generateContent({
    model: "gemini-3.1-pro-preview",
    contents: prompt,
    config: {
      tools: [{ googleSearch: {} }],
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          propertySpecs: {
            type: Type.OBJECT,
            properties: {
              sqft: { type: Type.NUMBER },
              beds: { type: Type.NUMBER },
              baths: { type: Type.NUMBER },
              yearBuilt: { type: Type.NUMBER },
              lotSize: { type: Type.STRING },
            },
            required: ["sqft", "beds", "baths", "yearBuilt", "lotSize"],
          },
          marketData: {
            type: Type.OBJECT,
            properties: {
              medianRent: { type: Type.NUMBER },
              avgRent: { type: Type.NUMBER },
              taxRate: { type: Type.NUMBER },
              insurancePremium: { type: Type.NUMBER },
              vacancyRate: { type: Type.NUMBER },
              appreciationRate: { type: Type.NUMBER },
              growthTrends: { type: Type.ARRAY, items: { type: Type.STRING } },
            },
            required: ["medianRent", "avgRent", "taxRate", "insurancePremium", "vacancyRate", "appreciationRate", "growthTrends"],
          },
          metrics: {
            type: Type.OBJECT,
            properties: {
              capRate: { type: Type.NUMBER },
              cashOnCash: { type: Type.NUMBER },
              grm: { type: Type.NUMBER },
              dscr: { type: Type.NUMBER },
              oer: { type: Type.NUMBER },
              noi: { type: Type.NUMBER },
              annualCashFlow: { type: Type.NUMBER },
              totalCashInvested: { type: Type.NUMBER },
            },
            required: ["capRate", "cashOnCash", "grm", "dscr", "oer", "noi", "annualCashFlow", "totalCashInvested"],
          },
          cashFlow: {
            type: Type.OBJECT,
            properties: {
              grossMonthlyIncome: { type: Type.NUMBER },
              fixedExpenses: {
                type: Type.OBJECT,
                properties: {
                  mortgage: { type: Type.NUMBER },
                  taxes: { type: Type.NUMBER },
                  insurance: { type: Type.NUMBER },
                  hoa: { type: Type.NUMBER },
                },
                required: ["mortgage", "taxes", "insurance", "hoa"],
              },
              variableExpenses: {
                type: Type.OBJECT,
                properties: {
                  maintenance: { type: Type.NUMBER },
                  vacancy: { type: Type.NUMBER },
                  capEx: { type: Type.NUMBER },
                  management: { type: Type.NUMBER },
                },
                required: ["maintenance", "vacancy", "capEx", "management"],
              },
              netMonthlyCashFlow: { type: Type.NUMBER },
            },
            required: ["grossMonthlyIncome", "fixedExpenses", "variableExpenses", "netMonthlyCashFlow"],
          },
          recommendation: {
            type: Type.OBJECT,
            properties: {
              decision: { type: Type.STRING, enum: ["BUY", "PASS"] },
              reasoning: { type: Type.STRING },
            },
            required: ["decision", "reasoning"],
          },
          riskAnalysis: {
            type: Type.OBJECT,
            properties: {
              redFlags: { type: Type.ARRAY, items: { type: Type.STRING } },
              opportunities: { type: Type.ARRAY, items: { type: Type.STRING } },
            },
            required: ["redFlags", "opportunities"],
          },
          forecast: {
            type: Type.OBJECT,
            properties: {
              appreciation: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    year: { type: Type.NUMBER },
                    rate: { type: Type.NUMBER },
                  },
                  required: ["year", "rate"],
                },
              },
              rentalDemand: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    year: { type: Type.NUMBER },
                    demandScore: { type: Type.NUMBER },
                    sentiment: { type: Type.STRING },
                  },
                  required: ["year", "demandScore", "sentiment"],
                },
              },
              fiveYearOutlook: { type: Type.STRING },
            },
            required: ["appreciation", "rentalDemand", "fiveYearOutlook"],
          },
          comparables: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                address: { type: Type.STRING },
                rent: { type: Type.NUMBER },
                type: { type: Type.STRING },
                features: { type: Type.ARRAY, items: { type: Type.STRING } },
                distance: { type: Type.STRING },
              },
              required: ["address", "rent", "type", "features", "distance"],
            },
          },
        },
        required: ["propertySpecs", "marketData", "metrics", "cashFlow", "recommendation", "riskAnalysis", "forecast", "comparables"],
      },
    },
  });

  return JSON.parse(response.text);
}
